### PR TITLE
Remove domain

### PR DESCRIPTION
**Pull request by KorySchneider**

### CODE REVIEW

**Comment by KorySchneider** [comment]
I'd rather not have my site on there, thanks.

Also not sure that it is vulnerable seeing as I have a site there...can you tell me more about this?

**Comment by cooler9711** [comment]
> Also not sure that it is vulnerable seeing as I have a site there

hence the potentially. not all of the domains on there are vulnerable, but a fair amount are. 

> can you tell me more about this? 

i use a program that scans domains and sees what A records they use in their dns. quite a few of the domains have nothing on there, and that leads to a 404 github page. if you route a github pages repo to the domain, you can put any static thing you want on that website.

**Comment by cooler9711** [comment]
but yeah, i’ll remove it

**Comment by KorySchneider** [comment]
Thanks!

**Pull request merged**
